language: go

go:
  - "1.6.2"

env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Kostiantyn Lysenko"
    - GIT_EMAIL="gshaud@gmail.com"
    - SOURCE_DIR="public"
    - DEPLOY_BRANCH="master"

before_install:
  - openssl aes-256-cbc -K $encrypted_d59617ad8abb_key -iv $encrypted_d59617ad8abb_iv -in travis_id_rsa.enc -out id_rsa -d

install:
  - true
  
before_script:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo

after_success:
 - echo "life.jakshi.com" > ./public/CNAME
 - ./scripts/deploy.sh
